config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  resources :users
  resources :locations
  resources :subjects
  resources :groups
  get 'users/create'

  get 'users/update'

  get 'users/destroy'

  get 'users/show'

  get 'users/index'

  get 'attendances/create'

  get 'attendances/update'

  get 'attendances/destroyindex'

  get 'attendances/show'

  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
    has_one :attendance
    belongs_to :subject
    belongs_to :group    
    belongs_to :location
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name,:group_id,:date,:subject_id,:location_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h4>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :group_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :group_id, Group.all.collect { |g| [ g.name, g.id ] },
       include_blank: true, class:"form-control", :selected => params[:cat_id]%>
       </div>
  </div>

  <div class="form-group">
    <%= f.label :subject_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :subject_id, Subject.all.collect { |s| [ s.name, s.id ] },
       include_blank: true, class:"form-control", :selected => params[:cat_id]%>
       </div>
  </div>

  <div class="form-group">
    <%= f.label :location_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :location_id, Location.all.collect { |l| [ l.name, l.id ] },
       include_blank: true, class:"form-control", :selected => params[:cat_id]%>
       </div>
  </div>
  
  
  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="page-header">
  <%= link_to events_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @event, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing event</h1>
</div>

<%= render 'form' %>

app/views/events/index.html.erb
<!-- only if you need custom infoboxes -->
<div class="page-header">
  <%= link_to new_event_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Event
  <% end %>
  <h1>Listing events</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Location</th>
            <th>Group</th>
            <th>Subject</th>
            <th colspan="3"></th>
            
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @events) do |event| %>
        <td><%= event.name %></td>
        <td><%= event.date %></td>
        <td><%= event.location.name %></td>
        <td><%= event.group.name %></td>
        <td><%= event.subject.name %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<div class="page-header">
  <%= link_to events_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New event</h1>
</div>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="page-header">
  <%= link_to events_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_event_path(@event), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show event</h1>
</div>

<dl class="dl-horizontal">

  <dt>Name:</dt>
  <dd><%= @event.name %></dd>


  <dt>Date:</dt>
  <dd><%= @event.date %></dd>
  <dt>Location:</dt>
  <dd><%= @event.location.name%></dd>
    <dt>Subject:</dt>
  <dd><%= @event.subject.name %></dd>
    <dt>Group:</dt>
  <dd><%= @event.group.name %></dd>

  <div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
</dl>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });
</script>