config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  resources :users
  resources :locations
  resources :subjects
  resources :groups
  get 'users/create'

  get 'users/update'

  get 'users/destroy'

  get 'users/show'

  get 'users/index'

  get 'attendances/create'

  get 'attendances/update'

  get 'attendances/destroyindex'

  get 'attendances/show'

  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "events#index"
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :events, dependent: :destroy
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :start, :finish)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @subject.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h4>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.time_select :start, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :finish, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.time_select :finish, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<div class="page-header">
  <%= link_to subjects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @subject, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing subject</h1>
</div>

<%= render 'form' %>

app/views/subjects/index.html.erb
<div class="page-header">
  <%= link_to new_subject_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Subject
  <% end %>
  <h1>Listing subjects</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Start</th>
            <th>Finish</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @subjects) do |subject| %>
            <td><%= subject.name %></td>
            <td><%= subject.start %></td>
            <td><%= subject.finish %></td>
            <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/subjects/new.html.erb
<div class="page-header">
  <%= link_to subjects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New subject</h1>
</div>

<%= render 'form' %>

app/views/subjects/show.html.erb
<div class="page-header">
  <%= link_to subjects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_subject_path(@subject), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show subject</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @subject.name %></dd>

  <dt>Start:</dt>
  <dd><%= @subject.start %></dd>

  <dt>Finish:</dt>
  <dd><%= @subject.finish %></dd>

</dl>